
from PyQt5 import QtWidgets, QtGui, QtCore,QMessageBox, QTableWidgetItem
import sqlite3

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1197, 857)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"background-color:gray;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setStyleSheet("QFrame{\n"
"background-color:#138D75;\n"
"    font: 12pt \"Microsoft Sans Serif\";\n"
"}\n"
"QTableWidget{\n"
"color:rgb(0,0,0);\n"
"gridline-color:rgb(0,206,151);\n"
"font-size:12pt;\n"
"}\n"
"QHeaderView::section{\n"
"background-color:rgb(0,206,151);\n"
"border:1px solid rgb(0,0,0);\n"
"font-size:12pt;\n"
"}\n"
"QTbaleWidget QTableCornerButton::section{\n"
"background-color:rgb(0,0,0);\n"
"border:1px solid  rgb(0,206,151);\n"
"}\n"
"QLineEdit{\n"
"border:2px solid rgb(0,0,0);\n"
"border-radius:20px;\n"
"background-color:#D0D3D4;\n"
"    font: 12pt \"Microsoft Sans Serif\";\n"
"}\n"
"QPushButton{\n"
"border-radius:20px;\n"
"border:2px solid rgb(0,0,0);\n"
"background-color:white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#CB4335;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title = QtWidgets.QLabel(self.frame_2)
        self.title.setObjectName("title")
        self.horizontalLayout.addWidget(self.title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.in_busqueda = QtWidgets.QLineEdit(self.frame_2)
        self.in_busqueda.setMinimumSize(QtCore.QSize(0, 40))
        self.in_busqueda.setObjectName("in_busqueda")
        self.horizontalLayout.addWidget(self.in_busqueda)
        self.btn_buscar = QtWidgets.QPushButton(self.frame_2)
        self.btn_buscar.setMinimumSize(QtCore.QSize(180, 50))
        self.btn_buscar.setMaximumSize(QtCore.QSize(180, 16777215))
        self.btn_buscar.setStyleSheet("")
        self.btn_buscar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ELEMENTOS GRAFICOS/buscar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_buscar.setIcon(icon)
        self.btn_buscar.setIconSize(QtCore.QSize(30, 30))
        self.btn_buscar.setObjectName("btn_buscar")
        self.horizontalLayout.addWidget(self.btn_buscar)
        self.verticalLayout_13.addLayout(self.horizontalLayout)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_10.addWidget(self.label_2)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.lbl_cedul = QtWidgets.QLabel(self.frame_2)
        self.lbl_cedul.setObjectName("lbl_cedul")
        self.horizontalLayout_18.addWidget(self.lbl_cedul)
        self.in_cedula = QtWidgets.QLineEdit(self.frame_2)
        self.in_cedula.setMinimumSize(QtCore.QSize(200, 40))
        self.in_cedula.setObjectName("in_cedula")
        self.horizontalLayout_18.addWidget(self.in_cedula)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_18)
        spacerItem1 = QtWidgets.QSpacerItem(448, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.lbl_gen = QtWidgets.QLabel(self.frame_2)
        self.lbl_gen.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_gen.setObjectName("lbl_gen")
        self.horizontalLayout_16.addWidget(self.lbl_gen)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_m = QtWidgets.QRadioButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.btn_m.setFont(font)
        self.btn_m.setStyleSheet("")
        self.btn_m.setObjectName("btn_m")
        self.horizontalLayout_5.addWidget(self.btn_m)
        self.btn_f = QtWidgets.QRadioButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.btn_f.setFont(font)
        self.btn_f.setObjectName("btn_f")
        self.horizontalLayout_5.addWidget(self.btn_f)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_16)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.lbl_name = QtWidgets.QLabel(self.frame_2)
        self.lbl_name.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_name.setObjectName("lbl_name")
        self.horizontalLayout_10.addWidget(self.lbl_name)
        self.in_name = QtWidgets.QLineEdit(self.frame_2)
        self.in_name.setMinimumSize(QtCore.QSize(200, 40))
        self.in_name.setObjectName("in_name")
        self.horizontalLayout_10.addWidget(self.in_name)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lbl_apell = QtWidgets.QLabel(self.frame_2)
        self.lbl_apell.setObjectName("lbl_apell")
        self.horizontalLayout_9.addWidget(self.lbl_apell)
        self.in_apell = QtWidgets.QLineEdit(self.frame_2)
        self.in_apell.setMinimumSize(QtCore.QSize(200, 40))
        self.in_apell.setObjectName("in_apell")
        self.horizontalLayout_9.addWidget(self.in_apell)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lbl_age = QtWidgets.QLabel(self.frame_2)
        self.lbl_age.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_age.setObjectName("lbl_age")
        self.horizontalLayout_8.addWidget(self.lbl_age)
        self.in_age = QtWidgets.QLineEdit(self.frame_2)
        self.in_age.setMinimumSize(QtCore.QSize(80, 40))
        self.in_age.setMaximumSize(QtCore.QSize(60, 16777215))
        self.in_age.setMaxLength(2)
        self.in_age.setAlignment(QtCore.Qt.AlignCenter)
        self.in_age.setClearButtonEnabled(False)
        self.in_age.setObjectName("in_age")
        self.horizontalLayout_8.addWidget(self.in_age)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbl_dir = QtWidgets.QLabel(self.frame_2)
        self.lbl_dir.setObjectName("lbl_dir")
        self.horizontalLayout_7.addWidget(self.lbl_dir)
        self.in_dir = QtWidgets.QLineEdit(self.frame_2)
        self.in_dir.setMinimumSize(QtCore.QSize(200, 40))
        self.in_dir.setObjectName("in_dir")
        self.horizontalLayout_7.addWidget(self.in_dir)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_number = QtWidgets.QLabel(self.frame_2)
        self.lbl_number.setObjectName("lbl_number")
        self.horizontalLayout_6.addWidget(self.lbl_number)
        self.in_number = QtWidgets.QLineEdit(self.frame_2)
        self.in_number.setMinimumSize(QtCore.QSize(200, 40))
        self.in_number.setObjectName("in_number")
        self.horizontalLayout_6.addWidget(self.in_number)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lbl_mail = QtWidgets.QLabel(self.frame_2)
        self.lbl_mail.setObjectName("lbl_mail")
        self.horizontalLayout_12.addWidget(self.lbl_mail)
        self.in_mail = QtWidgets.QLineEdit(self.frame_2)
        self.in_mail.setMinimumSize(QtCore.QSize(200, 40))
        self.in_mail.setObjectName("in_mail")
        self.horizontalLayout_12.addWidget(self.in_mail)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_12)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lbl_espec = QtWidgets.QLabel(self.frame_2)
        self.lbl_espec.setObjectName("lbl_espec")
        self.horizontalLayout_13.addWidget(self.lbl_espec)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_13.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.in_espec = QtWidgets.QLineEdit(self.frame_2)
        self.in_espec.setMinimumSize(QtCore.QSize(200, 40))
        self.in_espec.setObjectName("in_espec")
        self.horizontalLayout_13.addWidget(self.in_espec)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbl_foto = QtWidgets.QLabel(self.frame_2)
        self.lbl_foto.setObjectName("lbl_foto")
        self.verticalLayout_4.addWidget(self.lbl_foto)
        self.foto = QtWidgets.QLabel(self.frame_2)
        self.foto.setMinimumSize(QtCore.QSize(200, 200))
        self.foto.setMaximumSize(QtCore.QSize(200, 200))
        self.foto.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(0, 0, 0);\n"
"border-radius:20px;\n"
"}")
        self.foto.setAlignment(QtCore.Qt.AlignCenter)
        self.foto.setObjectName("foto")
        self.verticalLayout_4.addWidget(self.foto)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem9)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_11)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.horizontalLayout_17.addLayout(self.verticalLayout_10)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem11)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setMinimumSize(QtCore.QSize(100, 20))
        self.label_3.setMaximumSize(QtCore.QSize(250, 20))
        self.label_3.setStyleSheet("QLabel{\n"
"border:0px;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem12)
        self.btn_agg = QtWidgets.QPushButton(self.frame_2)
        self.btn_agg.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_agg.setMaximumSize(QtCore.QSize(150, 50))
        self.btn_agg.setObjectName("btn_agg")
        self.verticalLayout_7.addWidget(self.btn_agg)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem13)
        self.btn_edit = QtWidgets.QPushButton(self.frame_2)
        self.btn_edit.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_edit.setMaximumSize(QtCore.QSize(150, 50))
        self.btn_edit.setObjectName("btn_edit")
        self.verticalLayout_7.addWidget(self.btn_edit)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem14)
        self.btn_clear = QtWidgets.QPushButton(self.frame_2)
        self.btn_clear.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_clear.setMaximumSize(QtCore.QSize(150, 50))
        self.btn_clear.setObjectName("btn_clear")
        self.verticalLayout_7.addWidget(self.btn_clear)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem15)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        self.horizontalLayout_17.addLayout(self.verticalLayout_6)
        self.verticalLayout_13.addLayout(self.horizontalLayout_17)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem16)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setStyleSheet("QFrame{\n"
"background-color:white;\n"
"border-radius:20px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabla_doctores = QtWidgets.QTableWidget(self.frame_3)
        self.tabla_doctores.setMinimumSize(QtCore.QSize(920, 0))
        self.tabla_doctores.setMaximumSize(QtCore.QSize(920, 16777215))
        self.tabla_doctores.setStyleSheet("")
        self.tabla_doctores.setObjectName("tabla_doctores")
        self.tabla_doctores.setColumnCount(9)
        self.tabla_doctores.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_doctores.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_doctores.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_doctores.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_doctores.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_doctores.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_doctores.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_doctores.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_doctores.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_doctores.setHorizontalHeaderItem(8, item)
        self.horizontalLayout_2.addWidget(self.tabla_doctores)
        spacerItem17 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem17)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setStyleSheet("QFrame{\n"
"background-color:gray;\n"
"border-radius:0px\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem18)
        self.btn_delete = QtWidgets.QPushButton(self.frame_4)
        self.btn_delete.setMinimumSize(QtCore.QSize(180, 50))
        self.btn_delete.setMaximumSize(QtCore.QSize(120, 50))
        self.btn_delete.setObjectName("btn_delete")
        self.verticalLayout_11.addWidget(self.btn_delete)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem19)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.verticalLayout_13.addWidget(self.frame_3)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1197, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Registro de datos de paciente"))
        self.label_2.setText(_translate("MainWindow", "Por favor, llene los campos con los respectivos datos del doctor para resgistrarlo en el sistema"))
        self.lbl_cedul.setText(_translate("MainWindow", "Cedula:"))
        self.lbl_gen.setText(_translate("MainWindow", "Sexo:"))
        self.btn_m.setText(_translate("MainWindow", "M"))
        self.btn_f.setText(_translate("MainWindow", "F"))
        self.lbl_name.setText(_translate("MainWindow", "Nombres:"))
        self.lbl_apell.setText(_translate("MainWindow", "Apellidos:"))
        self.lbl_age.setText(_translate("MainWindow", "Edad:"))
        self.lbl_dir.setText(_translate("MainWindow", "Direccion:"))
        self.lbl_number.setText(_translate("MainWindow", "Telefono:"))
        self.lbl_mail.setText(_translate("MainWindow", "E-mail:"))
        self.lbl_espec.setText(_translate("MainWindow", "Especialidad:"))
        self.lbl_foto.setText(_translate("MainWindow", "Cargue una foto del Doctor"))
        self.foto.setText(_translate("MainWindow", "Foto"))
        self.label_3.setText(_translate("MainWindow", "Controles"))
        self.btn_agg.setText(_translate("MainWindow", "Agregar"))
        self.btn_edit.setText(_translate("MainWindow", "Editar"))
        self.btn_clear.setText(_translate("MainWindow", "Limpiar"))
        item = self.tabla_doctores.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Cedula"))
        item = self.tabla_doctores.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombres"))
        item = self.tabla_doctores.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Apellidos"))
        item = self.tabla_doctores.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Edad"))
        item = self.tabla_doctores.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Sexo"))
        item = self.tabla_doctores.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Dirección"))
        item = self.tabla_doctores.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Telefono"))
        item = self.tabla_doctores.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "E-mail"))
        item = self.tabla_doctores.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Especialidad"))
        self.btn_delete.setText(_translate("MainWindow", "Eliminar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Datos basicos del doctor"))
