# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\reybe\OneDrive\Escritorio\project\interfaces\eliminarData.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(525, 392)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 641, 641))
        self.frame.setStyleSheet("background-color:rgba(149,200,249);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(150, 20, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 200, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.ln_repeatPassword = QtWidgets.QLineEdit(self.frame)
        self.ln_repeatPassword.setGeometry(QtCore.QRect(290, 210, 191, 31))
        self.ln_repeatPassword.setStyleSheet("border-radius:15px;\n"
"background-color:rgba(0,0,0,0.5);\n"
"color:white;\n"
"font-size:13px;")
        self.ln_repeatPassword.setObjectName("ln_repeatPassword")
        self.bt_delete = QtWidgets.QPushButton(self.frame)
        self.bt_delete.setGeometry(QtCore.QRect(340, 330, 121, 51))
        self.bt_delete.setStyleSheet("QPushButton{\n"
"border-radius:25px;\n"
"background-color:rgb(255, 23, 116);\n"
"\n"
"color:white;\n"
"font-size:18px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(100, 50, 130);\n"
"}")
        self.bt_delete.setObjectName("bt_delete")
        self.bt_back = QtWidgets.QPushButton(self.frame)
        self.bt_back.setGeometry(QtCore.QRect(60, 320, 121, 51))
        self.bt_back.setStyleSheet("QPushButton{\n"
"border-radius:25px;\n"
"background-color:rgb(255, 23, 116);\n"
"\n"
"color:white;\n"
"font-size:18px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(100, 50, 130);\n"
"}")
        self.bt_back.setObjectName("bt_back")
        self.ln_password = QtWidgets.QLineEdit(self.frame)
        self.ln_password.setGeometry(QtCore.QRect(290, 130, 191, 31))
        self.ln_password.setStyleSheet("border-radius:15px;\n"
"background-color:rgba(0,0,0,0.5);\n"
"color:white;\n"
"font-size:13px;")
        self.ln_password.setObjectName("ln_password")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Eliminar Data"))
        self.label_2.setText(_translate("MainWindow", "Ingrese su contraseña"))
        self.label_3.setText(_translate("MainWindow", "Repita su contraseña"))
        self.bt_delete.setText(_translate("MainWindow", "Eliminar"))
        self.bt_back.setText(_translate("MainWindow", "Volver"))
