# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/reinaldo/Documentos/dev/App-Consultas-y-Historias-Medicas/interfaces/help.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(432, 406)
        Dialog.setStyleSheet("background-color:rgb(70, 130, 169);\n"
"\n"
"")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 0, 71, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/home/reinaldo/Documentos/dev/App-Consultas-y-Historias-Medicas/interfaces/ELEMENTOS GRAFICOS/help.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(150, 70, 131, 31))
        self.label_6.setStyleSheet("font-size:18px;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(60, 160, 121, 111))
        self.label_9.setStyleSheet("border-radius:20px;")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("/home/reinaldo/Documentos/dev/App-Consultas-y-Historias-Medicas/interfaces/ELEMENTOS GRAFICOS/reinaldo.jpg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(230, 160, 121, 111))
        self.label_10.setStyleSheet("border-radius:20px;")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("/home/reinaldo/Documentos/dev/App-Consultas-y-Historias-Medicas/interfaces/ELEMENTOS GRAFICOS/cesar.jpg"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.github = QtWidgets.QLabel(Dialog)
        self.github.setGeometry(QtCore.QRect(180, 280, 71, 61))
        self.github.setText("")
        self.github.setPixmap(QtGui.QPixmap("/home/reinaldo/Documentos/dev/App-Consultas-y-Historias-Medicas/interfaces/ELEMENTOS GRAFICOS/github.png"))
        self.github.setScaledContents(True)
        self.github.setObjectName("github")
        self.click = QtWidgets.QLabel(Dialog)
        self.click.setGeometry(QtCore.QRect(160, 350, 111, 20))
        self.click.setStyleSheet("font-size:14px;\n"
"text-decoration:none;\n"
"color:blue;")
        self.click.setScaledContents(True)
        self.click.setAlignment(QtCore.Qt.AlignCenter)
        self.click.setObjectName("click")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(41, 111, 371, 24))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setStyleSheet("font-size:18px;")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setStyleSheet("font-size:18px;")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_6.setText(_translate("Dialog", "Realizado por"))
        self.click.setText(_translate("Dialog", "Haz click"))
        self.label_7.setText(_translate("Dialog", "Reinaldo Bellorin"))
        self.label_8.setText(_translate("Dialog", "Cesar Perozo"))
