# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\reybe\OneDrive\Escritorio\project\interfaces\menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(891, 701)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color:rgb(70, 130, 169);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superior = QtWidgets.QFrame(self.frame)
        self.frame_superior.setEnabled(True)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 42))
        self.frame_superior.setStyleSheet("QFrame{\n"
"background-color:rgb(0, 85, 127);\n"
"border-radius:25px;\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bt_menu = QtWidgets.QPushButton(self.frame_superior)
        self.bt_menu.setMinimumSize(QtCore.QSize(50, 50))
        self.bt_menu.setStyleSheet("QPushButton{\n"
"border-radius:25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:white;\n"
"background-color:rgb(145, 200, 228);\n"
"\n"
"}\n"
"")
        self.bt_menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\project\\interfaces\\ELEMENTOS GRAFICOS/bar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_menu.setIcon(icon)
        self.bt_menu.setIconSize(QtCore.QSize(38, 38))
        self.bt_menu.setObjectName("bt_menu")
        self.horizontalLayout_2.addWidget(self.bt_menu)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_10 = QtWidgets.QLabel(self.frame_superior)
        self.label_10.setStyleSheet("font: 26pt \"MS Reference Sans Serif\";")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.bt_info = QtWidgets.QPushButton(self.frame_superior)
        self.bt_info.setMinimumSize(QtCore.QSize(50, 50))
        self.bt_info.setStyleSheet("QPushButton{\n"
"border-radius:25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:white;\n"
"background-color:rgb(145, 200, 228);\n"
"\n"
"}\n"
"")
        self.bt_info.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\project\\interfaces\\ELEMENTOS GRAFICOS/profile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_info.setIcon(icon1)
        self.bt_info.setIconSize(QtCore.QSize(38, 38))
        self.bt_info.setObjectName("bt_info")
        self.horizontalLayout_2.addWidget(self.bt_info)
        self.bt_salir = QtWidgets.QPushButton(self.frame_superior)
        self.bt_salir.setMinimumSize(QtCore.QSize(50, 50))
        self.bt_salir.setStyleSheet("QPushButton{\n"
"border-radius:25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:white;\n"
"background-color:rgb(145, 200, 228);\n"
"\n"
"}\n"
"")
        self.bt_salir.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\project\\interfaces\\ELEMENTOS GRAFICOS/exit-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_salir.setIcon(icon2)
        self.bt_salir.setIconSize(QtCore.QSize(38, 38))
        self.bt_salir.setObjectName("bt_salir")
        self.horizontalLayout_2.addWidget(self.bt_salir)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.frame_superior)
        self.frame_contenido = QtWidgets.QFrame(self.frame)
        self.frame_contenido.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_contenido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contenido.setObjectName("frame_contenido")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_contenido)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_opciones = QtWidgets.QFrame(self.frame_contenido)
        self.frame_opciones.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_opciones.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_opciones.setStyleSheet("QFrame{\n"
"background-color:rgb(246, 244, 235);\n"
"border-radius:25px;\n"
"}\n"
"QLabel{\n"
"    font: 12pt \"MS Reference Sans Serif\";\n"
"}\n"
"")
        self.frame_opciones.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_opciones.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_opciones.setObjectName("frame_opciones")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_opciones)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(self.frame_opciones)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.bt_home = QtWidgets.QPushButton(self.frame_opciones)
        self.bt_home.setMinimumSize(QtCore.QSize(50, 50))
        self.bt_home.setStyleSheet("QPushButton{\n"
"border-radius:25px;\n"
"background-color:rgb(246, 244, 235);\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"background-color:rgb(145, 200, 228);\n"
"\n"
"}")
        self.bt_home.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\project\\interfaces\\ELEMENTOS GRAFICOS/casa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_home.setIcon(icon3)
        self.bt_home.setIconSize(QtCore.QSize(38, 38))
        self.bt_home.setObjectName("bt_home")
        self.verticalLayout_3.addWidget(self.bt_home)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.label_6 = QtWidgets.QLabel(self.frame_opciones)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.bt_registro = QtWidgets.QPushButton(self.frame_opciones)
        self.bt_registro.setMinimumSize(QtCore.QSize(50, 50))
        self.bt_registro.setStyleSheet("QPushButton{\n"
"border-radius:25px;\n"
"background-color:rgb(246, 244, 235);\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"background-color:rgb(145, 200, 228);\n"
"\n"
"}\n"
"")
        self.bt_registro.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\project\\interfaces\\ELEMENTOS GRAFICOS/doctor-48-regular.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_registro.setIcon(icon4)
        self.bt_registro.setIconSize(QtCore.QSize(38, 38))
        self.bt_registro.setObjectName("bt_registro")
        self.verticalLayout_3.addWidget(self.bt_registro)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.label_7 = QtWidgets.QLabel(self.frame_opciones)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.bt_paciente = QtWidgets.QPushButton(self.frame_opciones)
        self.bt_paciente.setMinimumSize(QtCore.QSize(50, 50))
        self.bt_paciente.setStyleSheet("QPushButton{\n"
"border-radius:25px;\n"
"background-color:rgb(246, 244, 235);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:white;\n"
"background-color:rgb(145, 200, 228);\n"
"\n"
"}\n"
"")
        self.bt_paciente.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\project\\interfaces\\ELEMENTOS GRAFICOS/medical.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_paciente.setIcon(icon5)
        self.bt_paciente.setIconSize(QtCore.QSize(38, 38))
        self.bt_paciente.setObjectName("bt_paciente")
        self.verticalLayout_3.addWidget(self.bt_paciente)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.label_8 = QtWidgets.QLabel(self.frame_opciones)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.bt_citas = QtWidgets.QPushButton(self.frame_opciones)
        self.bt_citas.setMinimumSize(QtCore.QSize(50, 50))
        self.bt_citas.setStyleSheet("QPushButton{\n"
"border-radius:25px;\n"
"background-color:rgb(246, 244, 235);\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"background-color:rgb(145, 200, 228);\n"
"\n"
"}\n"
"")
        self.bt_citas.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\project\\interfaces\\ELEMENTOS GRAFICOS/work-history.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_citas.setIcon(icon6)
        self.bt_citas.setIconSize(QtCore.QSize(38, 38))
        self.bt_citas.setObjectName("bt_citas")
        self.verticalLayout_3.addWidget(self.bt_citas)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.label_9 = QtWidgets.QLabel(self.frame_opciones)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.bt_historial = QtWidgets.QPushButton(self.frame_opciones)
        self.bt_historial.setMinimumSize(QtCore.QSize(50, 50))
        self.bt_historial.setStyleSheet("QPushButton{\n"
"border-radius:25px;\n"
"background-color:rgb(246, 244, 235);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:white;\n"
"background-color:rgb(145, 200, 228);\n"
"\n"
"}\n"
"")
        self.bt_historial.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\project\\interfaces\\ELEMENTOS GRAFICOS/sharp-update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_historial.setIcon(icon7)
        self.bt_historial.setIconSize(QtCore.QSize(38, 38))
        self.bt_historial.setObjectName("bt_historial")
        self.verticalLayout_3.addWidget(self.bt_historial)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addWidget(self.frame_opciones)
        self.frame_paginas = QtWidgets.QFrame(self.frame_contenido)
        self.frame_paginas.setStyleSheet("")
        self.frame_paginas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_paginas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_paginas.setObjectName("frame_paginas")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_paginas)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_paginas)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.lb_nombre = QtWidgets.QLabel(self.page_home)
        self.lb_nombre.setGeometry(QtCore.QRect(180, 30, 371, 51))
        self.lb_nombre.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lb_nombre.setStyleSheet("font: 75 italic 18px \"Hack Nerd Font\";\n"
"")
        self.lb_nombre.setText("")
        self.lb_nombre.setTextFormat(QtCore.Qt.AutoText)
        self.lb_nombre.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_nombre.setObjectName("lb_nombre")
        self.stackedWidget.addWidget(self.page_home)
        self.page_registro = QtWidgets.QWidget()
        self.page_registro.setObjectName("page_registro")
        self.label_2 = QtWidgets.QLabel(self.page_registro)
        self.label_2.setGeometry(QtCore.QRect(170, 40, 201, 16))
        self.label_2.setStyleSheet("font: 75 italic 18px \"Hack Nerd Font\";")
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page_registro)
        self.page_consulta = QtWidgets.QWidget()
        self.page_consulta.setObjectName("page_consulta")
        self.label_3 = QtWidgets.QLabel(self.page_consulta)
        self.label_3.setGeometry(QtCore.QRect(190, 50, 201, 16))
        self.label_3.setStyleSheet("font: 75 italic 18px \"Hack Nerd Font\";")
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page_consulta)
        self.page_pacientes = QtWidgets.QWidget()
        self.page_pacientes.setObjectName("page_pacientes")
        self.label_4 = QtWidgets.QLabel(self.page_pacientes)
        self.label_4.setGeometry(QtCore.QRect(170, 30, 201, 16))
        self.label_4.setStyleSheet("font: 75 italic 18px \"Hack Nerd Font\";")
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page_pacientes)
        self.page_historial = QtWidgets.QWidget()
        self.page_historial.setObjectName("page_historial")
        self.label_5 = QtWidgets.QLabel(self.page_historial)
        self.label_5.setGeometry(QtCore.QRect(170, 40, 201, 16))
        self.label_5.setStyleSheet("font: 75 italic 18px \"Hack Nerd Font\";")
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.page_historial)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.frame_paginas)
        self.frame_paginas.raise_()
        self.frame_opciones.raise_()
        self.verticalLayout_2.addWidget(self.frame_contenido)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 8)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_10.setText(_translate("MainWindow", "Menu principal"))
        self.label.setText(_translate("MainWindow", "Home"))
        self.label_6.setText(_translate("MainWindow", "Registro de pacientes"))
        self.label_7.setText(_translate("MainWindow", "Placas dentales"))
        self.label_8.setText(_translate("MainWindow", "Agendar citas"))
        self.label_9.setText(_translate("MainWindow", "Agendar citas"))
        self.label_2.setText(_translate("MainWindow", "PAGINA REGISTRO"))
        self.label_3.setText(_translate("MainWindow", "PAGINA CONSULTA"))
        self.label_4.setText(_translate("MainWindow", "PAGINA PACIENTES"))
        self.label_5.setText(_translate("MainWindow", "PAGINA HISTORIAL"))
