# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/reinaldo/Documentos/dev/App-Consultas-y-Historias-Medicas/interfaces/pdfui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 648)
        MainWindow.setStyleSheet("background-color:blue;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 50, 155, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.bt_buscar = QtWidgets.QPushButton(self.centralwidget)
        self.bt_buscar.setGeometry(QtCore.QRect(153, 80, 121, 32))
        self.bt_buscar.setStyleSheet("color:black;\n"
"border-radius:15px;\n"
"background-color:white;")
        self.bt_buscar.setObjectName("bt_buscar")
        self.bt_preview = QtWidgets.QPushButton(self.centralwidget)
        self.bt_preview.setGeometry(QtCore.QRect(160, 420, 121, 32))
        self.bt_preview.setStyleSheet("color:black;\n"
"border-radius:15px;\n"
"background-color:white;")
        self.bt_preview.setObjectName("bt_preview")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(180, 140, 461, 261))
        self.treeWidget.setObjectName("treeWidget")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Pacientes Registrados"))
        self.bt_buscar.setText(_translate("MainWindow", "Buscar "))
        self.bt_preview.setText(_translate("MainWindow", "Vistar Previa"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Cedula"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Nombre"))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "Apellido"))
        self.treeWidget.headerItem().setText(3, _translate("MainWindow", "Edad"))
        self.treeWidget.headerItem().setText(4, _translate("MainWindow", "Sexo"))
