# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/reinaldo/Documentos/dev/App-Consultas-y-Historias-Medicas/interfaces/placas.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_placas(object):
    def setupUi(self, placas):
        placas.setObjectName("placas")
        placas.resize(1099, 753)
        self.centralwidget = QtWidgets.QWidget(placas)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"background-color:rgb(0, 85, 127);\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_7 = QtWidgets.QFrame(self.tab)
        self.frame_7.setStyleSheet("QFrame{\n"
"background-color:rgb(70, 130, 169);\n"
"    font: 14pt \"Microsoft Sans Serif\";\n"
"}\n"
"QTableWidget{\n"
"color:rgb(0,0,0);\n"
"gridline-color:rgb(0,206,151);\n"
"font-size:12pt;\n"
"}\n"
"QHeaderView::section{\n"
"background-color:rgb(0,206,151);\n"
"border:1px solid rgb(0,0,0);\n"
"    font: 12pt \"Microsoft Sans Serif\";\n"
"}\n"
"QTbaleWidget QTableCornerButton::section{\n"
"background-color:rgb(0,0,0);\n"
"border:1px solid  rgb(0,206,151);\n"
"}\n"
"QLineEdit{\n"
"border:2px solid rgb(0,0,0);\n"
"border-radius:20px;\n"
"    font: 12pt \"Microsoft Sans Serif\";\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton{\n"
"border-radius:20px;\n"
"border:2px solid rgb(0,0,0);\n"
"background-color:white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#5DADE2;\n"
"}\n"
"QTextEdit{\n"
"border:4px solid rgb(0,0,0);\n"
"border-radius:20px;\n"
"    font: 12pt \"Microsoft Sans Serif\";\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit::hover{\n"
"    background-color:#5DADE2;\n"
"}\n"
"QRadioButton{\n"
"    font: 14pt \"Microsoft Sans Serif\";\n"
"}\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.title_3 = QtWidgets.QLabel(self.frame_7)
        self.title_3.setObjectName("title_3")
        self.horizontalLayout_19.addWidget(self.title_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem)
        self.in_busqueda = QtWidgets.QLineEdit(self.frame_7)
        self.in_busqueda.setMinimumSize(QtCore.QSize(0, 40))
        self.in_busqueda.setObjectName("in_busqueda")
        self.horizontalLayout_19.addWidget(self.in_busqueda)
        self.btn_buscar = QtWidgets.QPushButton(self.frame_7)
        self.btn_buscar.setMinimumSize(QtCore.QSize(80, 40))
        self.btn_buscar.setMaximumSize(QtCore.QSize(80, 40))
        self.btn_buscar.setStyleSheet("")
        self.btn_buscar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/reinaldo/Documentos/dev/App-Consultas-y-Historias-Medicas/interfaces/ELEMENTOS GRAFICOS/buscar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_buscar.setIcon(icon)
        self.btn_buscar.setIconSize(QtCore.QSize(30, 30))
        self.btn_buscar.setObjectName("btn_buscar")
        self.horizontalLayout_19.addWidget(self.btn_buscar)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.lbl_name_3 = QtWidgets.QLabel(self.frame_7)
        self.lbl_name_3.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_name_3.setObjectName("lbl_name_3")
        self.horizontalLayout_21.addWidget(self.lbl_name_3)
        self.in_name = QtWidgets.QLineEdit(self.frame_7)
        self.in_name.setMinimumSize(QtCore.QSize(200, 40))
        self.in_name.setMaximumSize(QtCore.QSize(200, 40))
        self.in_name.setReadOnly(True)
        self.in_name.setObjectName("in_name")
        self.horizontalLayout_21.addWidget(self.in_name)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem1)
        self.verticalLayout_23.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.lbl_apell_3 = QtWidgets.QLabel(self.frame_7)
        self.lbl_apell_3.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_apell_3.setObjectName("lbl_apell_3")
        self.horizontalLayout_22.addWidget(self.lbl_apell_3)
        self.in_apell = QtWidgets.QLineEdit(self.frame_7)
        self.in_apell.setMinimumSize(QtCore.QSize(200, 40))
        self.in_apell.setMaximumSize(QtCore.QSize(200, 40))
        self.in_apell.setReadOnly(True)
        self.in_apell.setObjectName("in_apell")
        self.horizontalLayout_22.addWidget(self.in_apell)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem2)
        self.verticalLayout_23.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_20.addLayout(self.verticalLayout_23)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.img1 = QtWidgets.QLabel(self.frame_7)
        self.img1.setMinimumSize(QtCore.QSize(200, 200))
        self.img1.setMaximumSize(QtCore.QSize(200, 200))
        self.img1.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(0,0,0);\n"
"}")
        self.img1.setScaledContents(True)
        self.img1.setAlignment(QtCore.Qt.AlignCenter)
        self.img1.setObjectName("img1")
        self.horizontalLayout_2.addWidget(self.img1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.img2 = QtWidgets.QLabel(self.frame_7)
        self.img2.setMinimumSize(QtCore.QSize(200, 200))
        self.img2.setMaximumSize(QtCore.QSize(200, 200))
        self.img2.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(0,0,0);\n"
"}")
        self.img2.setScaledContents(True)
        self.img2.setAlignment(QtCore.Qt.AlignCenter)
        self.img2.setObjectName("img2")
        self.horizontalLayout_2.addWidget(self.img2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.img3 = QtWidgets.QLabel(self.frame_7)
        self.img3.setMinimumSize(QtCore.QSize(200, 200))
        self.img3.setMaximumSize(QtCore.QSize(200, 200))
        self.img3.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(0,0,0);\n"
"}")
        self.img3.setScaledContents(True)
        self.img3.setAlignment(QtCore.Qt.AlignCenter)
        self.img3.setObjectName("img3")
        self.horizontalLayout_2.addWidget(self.img3)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.img4 = QtWidgets.QLabel(self.frame_7)
        self.img4.setMinimumSize(QtCore.QSize(200, 200))
        self.img4.setMaximumSize(QtCore.QSize(200, 200))
        self.img4.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(0,0,0);\n"
"}")
        self.img4.setScaledContents(True)
        self.img4.setAlignment(QtCore.Qt.AlignCenter)
        self.img4.setObjectName("img4")
        self.horizontalLayout_3.addWidget(self.img4)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.img5 = QtWidgets.QLabel(self.frame_7)
        self.img5.setMinimumSize(QtCore.QSize(200, 200))
        self.img5.setMaximumSize(QtCore.QSize(200, 200))
        self.img5.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(0,0,0);\n"
"}")
        self.img5.setScaledContents(True)
        self.img5.setAlignment(QtCore.Qt.AlignCenter)
        self.img5.setObjectName("img5")
        self.horizontalLayout_3.addWidget(self.img5)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem13)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        self.btn_import = QtWidgets.QPushButton(self.frame_7)
        self.btn_import.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_import.setMaximumSize(QtCore.QSize(150, 50))
        self.btn_import.setObjectName("btn_import")
        self.horizontalLayout.addWidget(self.btn_import)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem15)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setSpacing(0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_12 = QtWidgets.QLabel(self.frame_7)
        self.label_12.setStyleSheet("QLabel{\n"
"background-color:white;\n"
"border-right:2px solid rgb(0,0,0);\n"
"border-left:2px solid rgb(0,0,0);\n"
"border-top:2px solid rgb(0,0,0);\n"
"}")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_31.addWidget(self.label_12)
        self.frame_10 = QtWidgets.QFrame(self.frame_7)
        self.frame_10.setStyleSheet("QFrame{\n"
"    background-color:#707B7C;\n"
"border-right:2px solid rgb(0,0,0);\n"
"border-left:2px solid rgb(0,0,0);\n"
"border-bottom:2px solid rgb(0,0,0);\n"
"border-top:2px solid rgb(0,0,0);\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_53 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        self.verticalLayout_63 = QtWidgets.QVBoxLayout()
        self.verticalLayout_63.setObjectName("verticalLayout_63")
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_63.addItem(spacerItem16)
        self.btn_agg = QtWidgets.QPushButton(self.frame_10)
        self.btn_agg.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_agg.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_agg.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/home/reinaldo/Documentos/dev/App-Consultas-y-Historias-Medicas/interfaces/ELEMENTOS GRAFICOS/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_agg.setIcon(icon1)
        self.btn_agg.setIconSize(QtCore.QSize(25, 25))
        self.btn_agg.setObjectName("btn_agg")
        self.verticalLayout_63.addWidget(self.btn_agg)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_63.addItem(spacerItem17)
        self.btn_edit = QtWidgets.QPushButton(self.frame_10)
        self.btn_edit.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_edit.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_edit.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/home/reinaldo/Documentos/dev/App-Consultas-y-Historias-Medicas/interfaces/ELEMENTOS GRAFICOS/editar-codigo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_edit.setIcon(icon2)
        self.btn_edit.setIconSize(QtCore.QSize(25, 25))
        self.btn_edit.setObjectName("btn_edit")
        self.verticalLayout_63.addWidget(self.btn_edit)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_63.addItem(spacerItem18)
        self.btn_clear = QtWidgets.QPushButton(self.frame_10)
        self.btn_clear.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_clear.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_clear.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("/home/reinaldo/Documentos/dev/App-Consultas-y-Historias-Medicas/interfaces/ELEMENTOS GRAFICOS/limpiar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_clear.setIcon(icon3)
        self.btn_clear.setIconSize(QtCore.QSize(25, 25))
        self.btn_clear.setObjectName("btn_clear")
        self.verticalLayout_63.addWidget(self.btn_clear)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_63.addItem(spacerItem19)
        self.verticalLayout_53.addLayout(self.verticalLayout_63)
        self.verticalLayout_31.addWidget(self.frame_10)
        self.horizontalLayout_6.addLayout(self.verticalLayout_31)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem20)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setStyleSheet("QFrame{\n"
"background-color:rgb(70, 130, 169);\n"
"    font: 14pt \"Microsoft Sans Serif\";\n"
"}\n"
"QTableWidget{\n"
"color:rgb(0,0,0);\n"
"gridline-color:rgb(0,206,151);\n"
"font-size:12pt;\n"
"}\n"
"QHeaderView::section{\n"
"background-color:rgb(0,206,151);\n"
"border:1px solid rgb(0,0,0);\n"
"    font: 12pt \"Microsoft Sans Serif\";\n"
"}\n"
"QTbaleWidget QTableCornerButton::section{\n"
"background-color:rgb(0,0,0);\n"
"border:1px solid  rgb(0,206,151);\n"
"}\n"
"QLineEdit{\n"
"border:2px solid rgb(0,0,0);\n"
"border-radius:20px;\n"
"    font: 12pt \"Microsoft Sans Serif\";\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton{\n"
"border-radius:20px;\n"
"border:2px solid rgb(0,0,0);\n"
"background-color:white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#5DADE2;\n"
"}\n"
"QTextEdit{\n"
"border:4px solid rgb(0,0,0);\n"
"border-radius:20px;\n"
"    font: 12pt \"Microsoft Sans Serif\";\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit::hover{\n"
"    background-color:#5DADE2;\n"
"}\n"
"QRadioButton{\n"
"    font: 14pt \"Microsoft Sans Serif\";\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.title_2 = QtWidgets.QLabel(self.frame_3)
        self.title_2.setObjectName("title_2")
        self.horizontalLayout_17.addWidget(self.title_2)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem21)
        self.in_busqueda_2 = QtWidgets.QLineEdit(self.frame_3)
        self.in_busqueda_2.setMinimumSize(QtCore.QSize(0, 40))
        self.in_busqueda_2.setObjectName("in_busqueda_2")
        self.horizontalLayout_17.addWidget(self.in_busqueda_2)
        self.btn_buscar_2 = QtWidgets.QPushButton(self.frame_3)
        self.btn_buscar_2.setMinimumSize(QtCore.QSize(80, 40))
        self.btn_buscar_2.setMaximumSize(QtCore.QSize(80, 40))
        self.btn_buscar_2.setStyleSheet("")
        self.btn_buscar_2.setText("")
        self.btn_buscar_2.setIcon(icon)
        self.btn_buscar_2.setIconSize(QtCore.QSize(30, 30))
        self.btn_buscar_2.setObjectName("btn_buscar_2")
        self.horizontalLayout_17.addWidget(self.btn_buscar_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_15.addWidget(self.label_8)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_name_2 = QtWidgets.QLabel(self.frame_3)
        self.lbl_name_2.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_name_2.setObjectName("lbl_name_2")
        self.horizontalLayout_5.addWidget(self.lbl_name_2)
        self.in_name_2 = QtWidgets.QLineEdit(self.frame_3)
        self.in_name_2.setMinimumSize(QtCore.QSize(200, 40))
        self.in_name_2.setMaximumSize(QtCore.QSize(200, 40))
        self.in_name_2.setReadOnly(True)
        self.in_name_2.setObjectName("in_name_2")
        self.horizontalLayout_5.addWidget(self.in_name_2)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem22)
        self.verticalLayout_14.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lbl_apell_2 = QtWidgets.QLabel(self.frame_3)
        self.lbl_apell_2.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_apell_2.setObjectName("lbl_apell_2")
        self.horizontalLayout_13.addWidget(self.lbl_apell_2)
        self.in_apell_2 = QtWidgets.QLineEdit(self.frame_3)
        self.in_apell_2.setMinimumSize(QtCore.QSize(200, 40))
        self.in_apell_2.setMaximumSize(QtCore.QSize(200, 40))
        self.in_apell_2.setReadOnly(True)
        self.in_apell_2.setObjectName("in_apell_2")
        self.horizontalLayout_13.addWidget(self.in_apell_2)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem23)
        self.verticalLayout_14.addLayout(self.horizontalLayout_13)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        self.verticalLayout_9.addLayout(self.verticalLayout_15)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem24)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem25)
        self.img6 = QtWidgets.QLabel(self.frame_3)
        self.img6.setMinimumSize(QtCore.QSize(200, 200))
        self.img6.setMaximumSize(QtCore.QSize(200, 200))
        self.img6.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(0,0,0);\n"
"}")
        self.img6.setScaledContents(True)
        self.img6.setAlignment(QtCore.Qt.AlignCenter)
        self.img6.setObjectName("img6")
        self.horizontalLayout_7.addWidget(self.img6)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem26)
        self.img7 = QtWidgets.QLabel(self.frame_3)
        self.img7.setMinimumSize(QtCore.QSize(200, 200))
        self.img7.setMaximumSize(QtCore.QSize(200, 200))
        self.img7.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(0,0,0);\n"
"}")
        self.img7.setScaledContents(True)
        self.img7.setAlignment(QtCore.Qt.AlignCenter)
        self.img7.setObjectName("img7")
        self.horizontalLayout_7.addWidget(self.img7)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem27)
        self.img8 = QtWidgets.QLabel(self.frame_3)
        self.img8.setMinimumSize(QtCore.QSize(200, 200))
        self.img8.setMaximumSize(QtCore.QSize(200, 200))
        self.img8.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(0,0,0);\n"
"}")
        self.img8.setScaledContents(True)
        self.img8.setAlignment(QtCore.Qt.AlignCenter)
        self.img8.setObjectName("img8")
        self.horizontalLayout_7.addWidget(self.img8)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem28)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem29)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem30)
        self.img9 = QtWidgets.QLabel(self.frame_3)
        self.img9.setMinimumSize(QtCore.QSize(200, 200))
        self.img9.setMaximumSize(QtCore.QSize(200, 200))
        self.img9.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(0,0,0);\n"
"}")
        self.img9.setScaledContents(True)
        self.img9.setAlignment(QtCore.Qt.AlignCenter)
        self.img9.setObjectName("img9")
        self.horizontalLayout_8.addWidget(self.img9)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem31)
        self.img10 = QtWidgets.QLabel(self.frame_3)
        self.img10.setMinimumSize(QtCore.QSize(200, 200))
        self.img10.setMaximumSize(QtCore.QSize(200, 200))
        self.img10.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(0,0,0);\n"
"}")
        self.img10.setScaledContents(True)
        self.img10.setAlignment(QtCore.Qt.AlignCenter)
        self.img10.setObjectName("img10")
        self.horizontalLayout_8.addWidget(self.img10)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem32)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        spacerItem33 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem33)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem34)
        self.btn_clear_2 = QtWidgets.QPushButton(self.frame_3)
        self.btn_clear_2.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_clear_2.setMaximumSize(QtCore.QSize(150, 50))
        self.btn_clear_2.setStyleSheet("QPushButton{\n"
"    font: 13pt \"Microsoft Sans Serif\";\n"
"}")
        self.btn_clear_2.setObjectName("btn_clear_2")
        self.horizontalLayout_4.addWidget(self.btn_clear_2)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem35)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        spacerItem36 = QtWidgets.QSpacerItem(20, 39, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem36)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.frame)
        placas.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(placas)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1099, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        placas.setMenuBar(self.menubar)
        self.actionSalir = QtWidgets.QAction(placas)
        self.actionSalir.setObjectName("actionSalir")
        self.actionVolver_al_menu_principal = QtWidgets.QAction(placas)
        self.actionVolver_al_menu_principal.setObjectName("actionVolver_al_menu_principal")
        self.menuMenu.addAction(self.actionVolver_al_menu_principal)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionSalir)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(placas)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(placas)

    def retranslateUi(self, placas):
        _translate = QtCore.QCoreApplication.translate
        placas.setWindowTitle(_translate("placas", "MainWindow"))
        self.title_3.setText(_translate("placas", "Importar placas dentales"))
        self.lbl_name_3.setText(_translate("placas", "Nombre:"))
        self.lbl_apell_3.setText(_translate("placas", "Apellido:"))
        self.img1.setText(_translate("placas", "Radiografia dental"))
        self.img2.setText(_translate("placas", "Radiografia dental"))
        self.img3.setText(_translate("placas", "Radiografia dental"))
        self.img4.setText(_translate("placas", "Radiografia dental"))
        self.img5.setText(_translate("placas", "Radiografia dental"))
        self.btn_import.setText(_translate("placas", "Importar"))
        self.label_12.setText(_translate("placas", "Controles"))
        self.btn_agg.setText(_translate("placas", "Agregar"))
        self.btn_edit.setText(_translate("placas", "Editar"))
        self.btn_clear.setText(_translate("placas", "Limpiar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("placas", "Importar Placas dentales"))
        self.title_2.setText(_translate("placas", "Visualizar placas dentales"))
        self.label_8.setText(_translate("placas", "Las placas dentales del paciente:"))
        self.lbl_name_2.setText(_translate("placas", "Nombre:"))
        self.lbl_apell_2.setText(_translate("placas", "Apellido:"))
        self.img6.setText(_translate("placas", "Radiografia dental"))
        self.img7.setText(_translate("placas", "Radiografia dental"))
        self.img8.setText(_translate("placas", "Radiografia dental"))
        self.img9.setText(_translate("placas", "Radiografia dental"))
        self.img10.setText(_translate("placas", "Radiografia dental"))
        self.btn_clear_2.setText(_translate("placas", "Limpiar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("placas", "Visualizar Placas"))
        self.menuMenu.setTitle(_translate("placas", "Menu"))
        self.actionSalir.setText(_translate("placas", "Salir"))
        self.actionVolver_al_menu_principal.setText(_translate("placas", "Volver al menu principal"))
