# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\reybe\OneDrive\Escritorio\project\interfaces\placas(nueva).ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_placas(object):
    def setupUi(self, placas):
        placas.setObjectName("placas")
        placas.resize(1063, 702)
        self.centralwidget = QtWidgets.QWidget(placas)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"background-color:gray;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_7 = QtWidgets.QFrame(self.tab)
        self.frame_7.setStyleSheet("QFrame{\n"
"background-color:#138D75;\n"
"    font: 12pt \"Microsoft Sans Serif\";\n"
"}\n"
"QTableWidget{\n"
"color:rgb(0,0,0);\n"
"gridline-color:rgb(0,206,151);\n"
"font-size:12pt;\n"
"}\n"
"QHeaderView::section{\n"
"background-color:rgb(0,206,151);\n"
"border:1px solid rgb(0,0,0);\n"
"font-size:12pt;\n"
"}\n"
"QTbaleWidget QTableCornerButton::section{\n"
"background-color:rgb(0,0,0);\n"
"border:1px solid  rgb(0,206,151);\n"
"}\n"
"QLineEdit{\n"
"border:2px solid rgb(0,0,0);\n"
"border-radius:20px;\n"
"background-color:#D0D3D4;\n"
"    font: 12pt \"Microsoft Sans Serif\";\n"
"}\n"
"QPushButton{\n"
"border-radius:20px;\n"
"border:2px solid rgb(0,0,0);\n"
"background-color:white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#CB4335;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.title_3 = QtWidgets.QLabel(self.frame_7)
        self.title_3.setObjectName("title_3")
        self.horizontalLayout_19.addWidget(self.title_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem)
        self.in_busqueda = QtWidgets.QLineEdit(self.frame_7)
        self.in_busqueda.setMinimumSize(QtCore.QSize(0, 40))
        self.in_busqueda.setObjectName("in_busqueda")
        self.horizontalLayout_19.addWidget(self.in_busqueda)
        self.btn_buscar = QtWidgets.QPushButton(self.frame_7)
        self.btn_buscar.setMinimumSize(QtCore.QSize(180, 50))
        self.btn_buscar.setMaximumSize(QtCore.QSize(180, 16777215))
        self.btn_buscar.setStyleSheet("")
        self.btn_buscar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\reybe\\OneDrive\\Escritorio\\project\\interfaces\\../../../../Desktop/PROYECTO/project/interfaces/ELEMENTOS GRAFICOS/buscar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_buscar.setIcon(icon)
        self.btn_buscar.setIconSize(QtCore.QSize(30, 30))
        self.btn_buscar.setObjectName("btn_buscar")
        self.horizontalLayout_19.addWidget(self.btn_buscar)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.lbl_name_3 = QtWidgets.QLabel(self.frame_7)
        self.lbl_name_3.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_name_3.setObjectName("lbl_name_3")
        self.horizontalLayout_21.addWidget(self.lbl_name_3)
        self.in_name = QtWidgets.QLineEdit(self.frame_7)
        self.in_name.setMinimumSize(QtCore.QSize(200, 40))
        self.in_name.setMaximumSize(QtCore.QSize(200, 40))
        self.in_name.setObjectName("in_name")
        self.horizontalLayout_21.addWidget(self.in_name)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem1)
        self.verticalLayout_23.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.lbl_apell_3 = QtWidgets.QLabel(self.frame_7)
        self.lbl_apell_3.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_apell_3.setObjectName("lbl_apell_3")
        self.horizontalLayout_22.addWidget(self.lbl_apell_3)
        self.in_apell = QtWidgets.QLineEdit(self.frame_7)
        self.in_apell.setMinimumSize(QtCore.QSize(200, 40))
        self.in_apell.setMaximumSize(QtCore.QSize(200, 40))
        self.in_apell.setObjectName("in_apell")
        self.horizontalLayout_22.addWidget(self.in_apell)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem2)
        self.verticalLayout_23.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_20.addLayout(self.verticalLayout_23)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.img1 = QtWidgets.QLabel(self.frame_7)
        self.img1.setMinimumSize(QtCore.QSize(250, 250))
        self.img1.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(0,0,0);\n"
"border-radius:20px;\n"
"}")
        self.img1.setAlignment(QtCore.Qt.AlignCenter)
        self.img1.setObjectName("img1")
        self.horizontalLayout_2.addWidget(self.img1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.img2 = QtWidgets.QLabel(self.frame_7)
        self.img2.setMinimumSize(QtCore.QSize(250, 250))
        self.img2.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(0,0,0);\n"
"border-radius:20px;\n"
"}")
        self.img2.setAlignment(QtCore.Qt.AlignCenter)
        self.img2.setObjectName("img2")
        self.horizontalLayout_2.addWidget(self.img2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.img3 = QtWidgets.QLabel(self.frame_7)
        self.img3.setMinimumSize(QtCore.QSize(250, 250))
        self.img3.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(0,0,0);\n"
"border-radius:20px;\n"
"}")
        self.img3.setAlignment(QtCore.Qt.AlignCenter)
        self.img3.setObjectName("img3")
        self.horizontalLayout_2.addWidget(self.img3)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.btn_import = QtWidgets.QPushButton(self.frame_7)
        self.btn_import.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_import.setMaximumSize(QtCore.QSize(150, 50))
        self.btn_import.setObjectName("btn_import")
        self.horizontalLayout.addWidget(self.btn_import)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.frame_7)
        self.label_13.setMinimumSize(QtCore.QSize(100, 20))
        self.label_13.setMaximumSize(QtCore.QSize(250, 20))
        self.label_13.setStyleSheet("QLabel{\n"
"border:0px;\n"
"}")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_6.addWidget(self.label_13)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem10)
        self.btn_agg = QtWidgets.QPushButton(self.frame_7)
        self.btn_agg.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_agg.setMaximumSize(QtCore.QSize(150, 50))
        self.btn_agg.setObjectName("btn_agg")
        self.verticalLayout_6.addWidget(self.btn_agg)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem11)
        self.btn_edit = QtWidgets.QPushButton(self.frame_7)
        self.btn_edit.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_edit.setMaximumSize(QtCore.QSize(150, 50))
        self.btn_edit.setObjectName("btn_edit")
        self.verticalLayout_6.addWidget(self.btn_edit)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem12)
        self.btn_clear = QtWidgets.QPushButton(self.frame_7)
        self.btn_clear.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_clear.setMaximumSize(QtCore.QSize(150, 50))
        self.btn_clear.setObjectName("btn_clear")
        self.verticalLayout_6.addWidget(self.btn_clear)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem13)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_24.addWidget(self.label_9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_24)
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setStyleSheet("QFrame{\n"
"background-color:white;\n"
"border-radius:20px;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.frame_9)
        self.tableWidget_3.setMinimumSize(QtCore.QSize(800, 0))
        self.tableWidget_3.setMaximumSize(QtCore.QSize(800, 16777215))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(7)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        self.tableWidget_3.horizontalHeader().setVisible(False)
        self.tableWidget_3.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(111)
        self.horizontalLayout_27.addWidget(self.tableWidget_3)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem14)
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setMinimumSize(QtCore.QSize(205, 0))
        self.frame_10.setStyleSheet("QFrame{\n"
"background-color:gray;\n"
"border-radius: 0px;\n"
"border: 2px solid rgb(0,0,0);\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        spacerItem15 = QtWidgets.QSpacerItem(173, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_29.addItem(spacerItem15)
        self.btn_delete = QtWidgets.QPushButton(self.frame_10)
        self.btn_delete.setMinimumSize(QtCore.QSize(180, 50))
        self.btn_delete.setMaximumSize(QtCore.QSize(180, 50))
        self.btn_delete.setObjectName("btn_delete")
        self.verticalLayout_29.addWidget(self.btn_delete)
        spacerItem16 = QtWidgets.QSpacerItem(173, 31, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_29.addItem(spacerItem16)
        self.verticalLayout_28.addLayout(self.verticalLayout_29)
        self.horizontalLayout_27.addWidget(self.frame_10)
        self.verticalLayout_7.addWidget(self.frame_9)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setStyleSheet("QFrame{\n"
"background-color:#138D75;\n"
"    font: 12pt \"Microsoft Sans Serif\";\n"
"}\n"
"QTableWidget{\n"
"color:rgb(0,0,0);\n"
"gridline-color:rgb(0,206,151);\n"
"font-size:12pt;\n"
"}\n"
"QHeaderView::section{\n"
"background-color:rgb(0,206,151);\n"
"border:1px solid rgb(0,0,0);\n"
"font-size:12pt;\n"
"}\n"
"QTbaleWidget QTableCornerButton::section{\n"
"background-color:rgb(0,0,0);\n"
"border:1px solid  rgb(0,206,151);\n"
"}\n"
"QLineEdit{\n"
"border:2px solid rgb(0,0,0);\n"
"border-radius:20px;\n"
"background-color:#D0D3D4;\n"
"    font: 12pt \"Microsoft Sans Serif\";\n"
"}\n"
"QPushButton{\n"
"border-radius:20px;\n"
"border:2px solid rgb(0,0,0);\n"
"background-color:white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#CB4335;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.title_2 = QtWidgets.QLabel(self.frame_3)
        self.title_2.setObjectName("title_2")
        self.horizontalLayout_17.addWidget(self.title_2)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem17)
        self.in_busqueda_2 = QtWidgets.QLineEdit(self.frame_3)
        self.in_busqueda_2.setMinimumSize(QtCore.QSize(0, 40))
        self.in_busqueda_2.setObjectName("in_busqueda_2")
        self.horizontalLayout_17.addWidget(self.in_busqueda_2)
        self.btn_buscar_2 = QtWidgets.QPushButton(self.frame_3)
        self.btn_buscar_2.setMinimumSize(QtCore.QSize(180, 50))
        self.btn_buscar_2.setMaximumSize(QtCore.QSize(180, 16777215))
        self.btn_buscar_2.setStyleSheet("")
        self.btn_buscar_2.setText("")
        self.btn_buscar_2.setIcon(icon)
        self.btn_buscar_2.setIconSize(QtCore.QSize(30, 30))
        self.btn_buscar_2.setObjectName("btn_buscar_2")
        self.horizontalLayout_17.addWidget(self.btn_buscar_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_15.addWidget(self.label_8)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_name_2 = QtWidgets.QLabel(self.frame_3)
        self.lbl_name_2.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_name_2.setObjectName("lbl_name_2")
        self.horizontalLayout_5.addWidget(self.lbl_name_2)
        self.in_name_2 = QtWidgets.QLineEdit(self.frame_3)
        self.in_name_2.setMinimumSize(QtCore.QSize(200, 40))
        self.in_name_2.setMaximumSize(QtCore.QSize(200, 40))
        self.in_name_2.setObjectName("in_name_2")
        self.horizontalLayout_5.addWidget(self.in_name_2)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem18)
        self.verticalLayout_14.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lbl_apell_2 = QtWidgets.QLabel(self.frame_3)
        self.lbl_apell_2.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_apell_2.setObjectName("lbl_apell_2")
        self.horizontalLayout_13.addWidget(self.lbl_apell_2)
        self.in_apell_2 = QtWidgets.QLineEdit(self.frame_3)
        self.in_apell_2.setMinimumSize(QtCore.QSize(200, 40))
        self.in_apell_2.setMaximumSize(QtCore.QSize(200, 40))
        self.in_apell_2.setObjectName("in_apell_2")
        self.horizontalLayout_13.addWidget(self.in_apell_2)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem19)
        self.verticalLayout_14.addLayout(self.horizontalLayout_13)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        self.verticalLayout_8.addLayout(self.verticalLayout_15)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem20)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem21)
        self.img4 = QtWidgets.QLabel(self.frame_3)
        self.img4.setMinimumSize(QtCore.QSize(250, 250))
        self.img4.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(0,0,0);\n"
"border-radius:20px;\n"
"}")
        self.img4.setAlignment(QtCore.Qt.AlignCenter)
        self.img4.setObjectName("img4")
        self.horizontalLayout_11.addWidget(self.img4)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem22)
        self.img5 = QtWidgets.QLabel(self.frame_3)
        self.img5.setMinimumSize(QtCore.QSize(250, 250))
        self.img5.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(0,0,0);\n"
"border-radius:20px;\n"
"}")
        self.img5.setAlignment(QtCore.Qt.AlignCenter)
        self.img5.setObjectName("img5")
        self.horizontalLayout_11.addWidget(self.img5)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem23)
        self.img6 = QtWidgets.QLabel(self.frame_3)
        self.img6.setMinimumSize(QtCore.QSize(250, 250))
        self.img6.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid  rgb(0,0,0);\n"
"border-radius:20px;\n"
"}")
        self.img6.setAlignment(QtCore.Qt.AlignCenter)
        self.img6.setObjectName("img6")
        self.horizontalLayout_11.addWidget(self.img6)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem24)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem25)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem26)
        self.btn_clear_2 = QtWidgets.QPushButton(self.frame_3)
        self.btn_clear_2.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_clear_2.setMaximumSize(QtCore.QSize(150, 50))
        self.btn_clear_2.setObjectName("btn_clear_2")
        self.horizontalLayout_4.addWidget(self.btn_clear_2)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem27)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        spacerItem28 = QtWidgets.QSpacerItem(20, 39, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem28)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.frame)
        placas.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(placas)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1063, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        placas.setMenuBar(self.menubar)
        self.actionSalir = QtWidgets.QAction(placas)
        self.actionSalir.setObjectName("actionSalir")
        self.menuMenu.addAction(self.actionSalir)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(placas)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(placas)

    def retranslateUi(self, placas):
        _translate = QtCore.QCoreApplication.translate
        placas.setWindowTitle(_translate("placas", "MainWindow"))
        self.title_3.setText(_translate("placas", "Importar placas dentales"))
        self.lbl_name_3.setText(_translate("placas", "Nombre:"))
        self.lbl_apell_3.setText(_translate("placas", "Apellido:"))
        self.img1.setText(_translate("placas", "Placa"))
        self.img2.setText(_translate("placas", "Placa"))
        self.img3.setText(_translate("placas", "Placa"))
        self.btn_import.setText(_translate("placas", "Importar"))
        self.label_13.setText(_translate("placas", "Controles"))
        self.btn_agg.setText(_translate("placas", "Agendar"))
        self.btn_edit.setText(_translate("placas", "Editar"))
        self.btn_clear.setText(_translate("placas", "Limpiar"))
        self.label_9.setText(_translate("placas", "Por favor, cargue las placas dnetales del paciente"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("placas", "ID_Placa"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("placas", "Cedula_P"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("placas", "Nombre_P"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("placas", "Apellido_P"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("placas", "Placa 1"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("placas", "Placa 2"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("placas", "PLaca 3"))
        self.btn_delete.setText(_translate("placas", "Eliminar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("placas", "Importar Placas dentales"))
        self.title_2.setText(_translate("placas", "Visualizar placas dentales"))
        self.label_8.setText(_translate("placas", "Las placas dentales del paciente:"))
        self.lbl_name_2.setText(_translate("placas", "Nombre:"))
        self.lbl_apell_2.setText(_translate("placas", "Apellido:"))
        self.img4.setText(_translate("placas", "Placa"))
        self.img5.setText(_translate("placas", "Placa"))
        self.img6.setText(_translate("placas", "Placa"))
        self.btn_clear_2.setText(_translate("placas", "Limpiar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("placas", "Visualizar Placas"))
        self.menuMenu.setTitle(_translate("placas", "Menu"))
        self.actionSalir.setText(_translate("placas", "Salir"))
