# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/reinaldo/Documentos/dev/App-Consultas-y-Historias-Medicas/interfaces/salida.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Historia(object):
    def setupUi(self, Historia):
        Historia.setObjectName("Historia")
        Historia.resize(1033, 819)
        self.centralwidget = QtWidgets.QWidget(Historia)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_50 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_50.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_50.setSpacing(0)
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.frame_P = QtWidgets.QFrame(self.centralwidget)
        self.frame_P.setStyleSheet("QFrame{\n"
"background-color:rgb(0, 85, 127);\n"
"}")
        self.frame_P.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_P.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_P.setObjectName("frame_P")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_P)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_P)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_make = QtWidgets.QWidget()
        self.tab_make.setObjectName("tab_make")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_make)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fondo = QtWidgets.QFrame(self.tab_make)
        self.fondo.setStyleSheet("QFrame{\n"
"background-color:rgb(70, 130, 169);\n"
"    font: 12pt \"Microsoft Sans Serif\";\n"
"}\n"
"QTableWidget{\n"
"color:rgb(0,0,0);\n"
"gridline-color:rgb(0,206,151);\n"
"font-size:12pt;\n"
"}\n"
"QHeaderView::section{\n"
"background-color:rgb(0,206,151);\n"
"border:1px solid rgb(0,0,0);\n"
"font: 75 12pt \"Microsoft Sans Serif\";\n"
"}\n"
"QTbaleWidget QTableCornerButton::section{\n"
"background-color:rgb(0,0,0);\n"
"border:1px solid  rgb(0,206,151);\n"
"}\n"
"QLineEdit{\n"
"border:2px solid rgb(0,0,0);\n"
"border-radius:20px;\n"
"    font: 12pt \"Microsoft Sans Serif\";\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton{\n"
"border-radius:20px;\n"
"border:2px solid rgb(0,0,0);\n"
"background-color:white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#CB4335;\n"
"}\n"
"QTextEdit{\n"
"border:4px solid rgb(0,0,0);\n"
"border-radius:20px;\n"
"    font: 12pt \"Microsoft Sans Serif\";\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.fondo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fondo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fondo.setObjectName("fondo")
        self.widget = QtWidgets.QWidget(self.fondo)
        self.widget.setGeometry(QtCore.QRect(30, 10, 747, 42))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.in_busqueda = QtWidgets.QLineEdit(self.widget)
        self.in_busqueda.setMinimumSize(QtCore.QSize(0, 40))
        self.in_busqueda.setObjectName("in_busqueda")
        self.horizontalLayout.addWidget(self.in_busqueda)
        self.btn_buscar = QtWidgets.QPushButton(self.widget)
        self.btn_buscar.setMinimumSize(QtCore.QSize(100, 40))
        self.btn_buscar.setMaximumSize(QtCore.QSize(180, 16777215))
        self.btn_buscar.setStyleSheet("")
        self.btn_buscar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/reinaldo/Documentos/dev/App-Consultas-y-Historias-Medicas/interfaces/ELEMENTOS GRAFICOS/buscar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_buscar.setIcon(icon)
        self.btn_buscar.setIconSize(QtCore.QSize(30, 30))
        self.btn_buscar.setObjectName("btn_buscar")
        self.horizontalLayout.addWidget(self.btn_buscar)
        self.verticalLayout_3.addWidget(self.fondo)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/home/reinaldo/Documentos/dev/App-Consultas-y-Historias-Medicas/interfaces/ELEMENTOS GRAFICOS/registro-dental.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_make, icon1, "")
        self.tab_view = QtWidgets.QWidget()
        self.tab_view.setObjectName("tab_view")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.tab_view)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setSpacing(0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.frame = QtWidgets.QFrame(self.tab_view)
        self.frame.setStyleSheet("QFrame{\n"
"background-color:rgb(70, 130, 169);\n"
"    font: 12pt \"Microsoft Sans Serif\";\n"
"}\n"
"QTableWidget{\n"
"color:rgb(0,0,0);\n"
"gridline-color:rgb(0,206,151);\n"
"font-size:12pt;\n"
"}\n"
"QHeaderView::section{\n"
"background-color:rgb(0,206,151);\n"
"border:1px solid rgb(0,0,0);\n"
"font-size:12pt;\n"
"}\n"
"QTbaleWidget QTableCornerButton::section{\n"
"background-color:rgb(0,0,0);\n"
"border:1px solid  rgb(0,206,151);\n"
"}\n"
"QLineEdit{\n"
"border:2px solid rgb(0,0,0);\n"
"border-radius:20px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Microsoft Sans Serif\";\n"
"}\n"
"QPushButton{\n"
"border-radius:20px;\n"
"border:2px solid rgb(0,0,0);\n"
"background-color:white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#CB4335;\n"
"}\n"
"QTextEdit{\n"
"border:4px solid rgb(0,0,0);\n"
"border-radius:20px;\n"
"    font: 12pt \"Microsoft Sans Serif\";\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox{\n"
"border:1px solid rgb(0,0,0);\n"
"    font: 12pt \"Microsoft Sans Serif\";\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_29.addWidget(self.frame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/home/reinaldo/Documentos/dev/App-Consultas-y-Historias-Medicas/interfaces/ELEMENTOS GRAFICOS/reconstruccion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_view, icon2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout_50.addWidget(self.frame_P)
        Historia.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Historia)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1033, 21))
        self.menubar.setObjectName("menubar")
        Historia.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Historia)
        self.statusbar.setObjectName("statusbar")
        Historia.setStatusBar(self.statusbar)

        self.retranslateUi(Historia)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Historia)

    def retranslateUi(self, Historia):
        _translate = QtCore.QCoreApplication.translate
        Historia.setWindowTitle(_translate("Historia", "MainWindow"))
        self.label.setText(_translate("Historia", "Por favor, realice uan busqueda del paciente para crear la historia"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_make), _translate("Historia", "Crear Historia Medica"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_view), _translate("Historia", "Visualizar Historia"))
